version: '3.7'
services:
    #frontend:
    #    ports:
    #      - "8081:80"
          
    catalog-api:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://0.0.0.0:80
          - PATH_BASE=/catalog-api
          - PORT=80
        env_file:
          - './dapr/envs/developer.env'
        ports:
          - "5103:80"
          #- "9103:81"
          #- "50001:50001"
    
    catalog-api-dapr:
        command: ["./daprd",
          "-app-id", "catalog-api",
          "-app-port", "80",
          "-log-level", "debug",
          "-placement-host-address", "dapr-placement:50000",
          "-config", "/configuration/config.yaml",
          "-components-path", "/components"
          ]
        volumes:
          - "./dapr/components/:/components"
          - "./dapr/configuration/:/configuration"

    envoy:
        volumes:
            - ./src/ApiGateways/Envoy:/etc/envoy
        ports:
            - "10000:10000"
            - "9901:9901"
            #- "5202:80"
            #- "15202:8001"
            #- "50008:50001"

    envoy-dapr:
        command: ["./daprd",
            "-app-id", "envoy",
            "-app-port", "10000",
            "-config", "/configuration/config.yaml",
            "-components-path", "/components"
            ]
        volumes:
            - "./dapr/components/:/components"
            - "./dapr/configuration/:/configuration"

    rabbitmq:
        environment:
          RABBITMQ_DEFAULT_USER: "sample"
          RABBITMQ_DEFAULT_PASS: "sAmple2021"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:        
            - "5672:5672"
            - "15672:15672"
        volumes:
        - ./storage/rabbitmqdata/lib/:/var/lib/rabbitmq/
        - ./storage/rabbitmqdata/log/:/var/log/rabbitmq/

    zipkin:
        ports:
        - "9411:9411"

    sqlserver:
        volumes:
        - ./storage/sqldata:/var/opt/sqlserver/data
        - ./storage/sqllog:/var/opt/sqlserver/log
        environment:
            SA_PASSWORD: "DaprSample12@="
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
    
    
    elasticsearch:
        ports:
        - 9200:9200
        volumes:
          - './storage/elasticsearch_data:/bitnami/elasticsearch/data'
    kibana:
        volumes:
          - "./storage/kibana_data:/bitnami/kibana"

    dapr-placement:
        command: ["./placement", "-port", "50000", "-log-level", "debug"]
        ports:
            - "50000:50000"

