services:
    #frontend:
    #    container_name: frontend
    #    image: ${DOCKER_REGISTRY-}frontend:${PLATFORM:-linux}-${TAG:-latest}
    #    build:
    #        context: src/Frontend/dapr-frontend-sample/
    #        dockerfile: Dockerfile
    #    depends_on:
    #        - envoy

    catalog-api:
        container_name: catalog-api
        image: ${DOCKER_REGISTRY-}catalogapi:${PLATFORM:-linux}-${TAG:-latest}
        build:
          context: .
          dockerfile: src/Services/Catalog-Api/Dockerfile
        depends_on:
          - rabbitmq
    
    catalog-api-dapr:
        container_name: catalog-api-dapr
        image: "daprio/daprd:1.0.0"
        network_mode: "service:catalog-api"
        depends_on:
          - catalog-api
          - rabbitmq

    rabbitmq:
        container_name: rabbit
        image: rabbitmq:3-management-alpine

    redis:
        container_name: redis
        image: redis:alpine

    envoy:
        container_name: envoy
        image: envoyproxy/envoy-alpine:v1.18-latest

    envoy-dapr:
        container_name: envoy-dapr
        image: "daprio/daprd:1.0.0"
        network_mode: "service:envoy"
        depends_on:
        - envoy
    
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin-slim
  

    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - 1433:1433

    elasticsearch:
        container_name: elastic-search
        image: docker.io/bitnami/elasticsearch:7

    kibana:
        container_name: kibana
        image: docker.io/bitnami/kibana:7
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch

    # Usato solo per gli Actor 
    dapr-placement:
        container_name: dapr-placement
        image: "daprio/dapr:1.0.0"